### ISSUE TITLE
NoClassDefFoundError for htsjdk > 2.11.0

### ISSUE THREAD

**Issue by dariober** [samtools/htsjdk#1071]
Hi- I get a `NoClassDefFoundError` for versions of htsjdk after 2.11.0. Am I doing something wrong? Here's the stack trace:

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/xerial/snappy/SnappyError
	at htsjdk.samtools.util.TempStreamFactory.getSnappyLoader(TempStreamFactory.java:42)
	at htsjdk.samtools.util.TempStreamFactory.wrapTempOutputStream(TempStreamFactory.java:74)
	at test.Main.main(Main.java:10)
Caused by: java.lang.ClassNotFoundException: org.xerial.snappy.SnappyError
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more
```

And this is how I can reproduce the issue on my system (MacOS 10.12.6, java 1.8 under Eclipse).

* Test program:

```
package test;

import htsjdk.samtools.util.TempStreamFactory;

public class Main {
	public static void main(String[] args) {
		TempStreamFactory x= new TempStreamFactory();
		x.wrapTempOutputStream(null, 1000);
	}
}
```

* This works fine if I put on my build path this jar: http://central.maven.org/maven2/com/github/samtools/htsjdk/2.11.0/htsjdk-2.11.0.jar

* If I use a later version, including the latest http://central.maven.org/maven2/com/github/samtools/htsjdk/2.14.1/htsjdk-2.14.1.jar, I get the exception above

(By the way, I don't need to use `TempStreamFactory` directly, but I see it is called when writing bam files.)

**Comment by dariober** [comment]
Thanks for replying magicDGS. I'm not sure I understand what you mean by disabling snappy. I have written out my test program above and run it as:

```
java -Dsnappy.disable=true -jar ~/Downloads/test_snappy.jar
```

Problem is still there though.

As an aside, I'm quite surprised by this as I thought the compiled htsjdk.jar contained all the classes necessary to make it work.

**Comment by magicDGS** [comment]
That command line was exactly what I meant with disabling snappy. How are you packaging your jar file? Maybe you are using an `htsjdk.jar` without dependencies, and that's causing the issue...

**Comment by dariober** [comment]
I'm using the jar provided by maven central (see link in my first post) assuming this is what one should use unless one wants to compile from source. When I export the jar from eclipse I choose the option *Extract required libraries into generated JAR*. The same if I choose *Package required libraries into generated JAR*

I also tried to compile from source but I couldn't (this may be a completely separate issue):

```
wget https://github.com/samtools/htsjdk/archive/2.14.1.tar.gz
tar zxvf htsjdk-2.14.1.tar.gz
cd htsjdk-2.14.1

./gradlew
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/db291g/Downloads/htsjdk-2.14.1/build.gradle' line: 52

* What went wrong:
A problem occurred evaluating root project 'htsjdk'.
> Cannot find '.git' directory

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 6.392 secs
```

I remember successfully compiling previous releases.

**Comment by magicDGS** [comment]
As I thought, you should also add the dependencies to your class path. HTSJDK have the following compile dependencies:

https://github.com/samtools/htsjdk/blob/e051a566748ee30c3bac50dce2a49230251c0918/build.gradle#L34-L39

You can also find them in the POM from Maven: https://search.maven.org/#artifactdetails%7Ccom.github.samtools%7Chtsjdk%7C2.14.1%7Cjar

This should be added at compile time, and it should be packaged in your `test_snappy.jar` with the `htsjdk.jar` itself.

---

For the compilation from source, the tarball file does not contain the git information and that's why it is failing; you need to clone the repository, checkout the tag for the release that you want and then use gradle (more info in #636)

**Comment by dariober** [comment]
Hi again magicDGS, sorry I kept quite. So what I'm going to do is to google up the six required packages and add them to my build path. That's fine, but is it the right way of going about it? Or is there a more automatic (and less error-prone) way of doing it? Of course, as a user I prefer the old way where the compiled jar from maven had all the dependencies included...!

(May I suggest making these instructions explicit in a README file?)

**Comment by magicDGS** [comment]
I am not a maintainer or anything. For doing automatically, I will use a build system as [Maven](https://maven.apache.org/) or [Gradle](https://gradle.org/), which manages dependencies and help building your uber-jar.

Here is a tutorial of a simple way of manage your dependencies and build your java application with gradle: https://spring.io/guides/gs/gradle/

**Comment by lbergelson** [comment]
@dariober  We changed the jar we publish because packaging all the dependencies can cause conflicts in downstream projects that rely on different versions of those dependencies.  We definitely encourage using a build management system like gradle or maven for your own project.  

If you want to make a single htsjdk jar that packages all the dependencies you can build one from source by using the `./gradlew shadowJar` command and then depend on that.

**Comment by dariober** [comment]
Thank you both! Yes, I think I should familiarize with a build management system. For the time being, `./gradlew shadowJar` is what I was looking for. In fact, now I see it is mentioned in the README file but I missed it (good old RTFM...).
