### ISSUE TITLE
How to create a SamReader from LineReader?

### ISSUE THREAD

**Issue by koreykiran** [samtools/htsjdk#1155]
I was actually using an older library, in which I was using LineReader to create SAMTextReader.
Now we are trying to migrate it to a newer version of htsjdk and I can't find a way to create a SamReader using a LineReader.

```Java
@Override
public List<? extends SeqSymmetry> processLines(BioSeq seq, LineReader lineReader) throws Exception {
   SAMTextReader str = new SAMTextReader(new AsciiTabixLineReader(lineReader), header,ValidationStringency.SILENT);
   SimpleSeqSpan seqSpan = new SimpleSeqSpan(seq.getMin(), seq.getMax(), seq);
   return parse(str.queryUnmapped(), seqSpan, false);
}
```

Any help appreciated.

**Comment by lbergelson** [comment]
@koreykiran Is it necessary that you create it directly from a `LineReader`?  The recommended way to open a reader now is to use `SamReaderFactory`.  If you have the path to the sam file you can do 

```
SamReaderFactory.makeDefault().open(IOUtils.getPath(filepath))
```

**Comment by koreykiran** [comment]
@lbergelson Thank you for the quick response.
I really don't have the path to the same file, all I have is the line reader.
Please take a look at the following file for more reference.

https://bitbucket.org/lorainelab/integrated-genome-browser/raw/a2bcde955eaf99116b96eb31fbeccc45e8cf1608/plugins/bam/src/main/java/org/lorainelab/igb/bam/SAM.java

**Comment by lbergelson** [comment]
Wow, it looks like you're upgrading from net.sf.samtools v1.111 which is ancient.  I'm surprised if this is the biggest problem you've run into. 

You've got me curious now so I tried checking out and building your project.  

I don't mean to overly snarky, but I want to verify: are you sure that the code you're upgrading actually does what you want right now?  

```
    @Override
    public List<? extends SeqSymmetry> processLines(BioSeq seq, LineReader lineReader) throws Exception {
        // LineTrackerI ignored, since the SAMTextReader hides the lines
        SAMTextReader str = new SAMTextReader(new AsciiTabixLineReader(lineReader), header, ValidationStringency.SILENT);
        SimpleSeqSpan seqSpan = new SimpleSeqSpan(seq.getMin(), seq.getMax(), seq);
        return parse(str.queryUnmapped(), seqSpan, false);
    }
```

It looks like it creates the sam reader, and then immediately below calls `str.queryUnmapped()` on it.  This is implemented as 
```
    public CloseableIterator<SAMRecord> queryUnmapped() {
        throw new UnsupportedOperationException("Cannot query SAM text files");
    }
```

Which makes me think that maybe that particular problematic method would be better off being retired rather than upgraded?  Or it could be replaced with a simple throw.  I tried removed the LineProcessor interface and methods from the SAM class and it built without any issues, so I suspect it may be ok to just drop those methods.  

You might also be able to merge the SAM and BAM classes by using the SamReaderFactory, which supports things like identifying if it's a SAM or BAM file, automatically finding the correct indexes, etc (including over http).

Let me know what you think.  Happy to try to help get you on a more recent version.  Sorry if I'm completely misunderstanding things.

**Comment by koreykiran** [comment]
@lbergelson  Yes, that's correct we are trying to upgrade from the ancient era to modern era.
I made the processLines method unsupported.
One other issue that I ran into was the readIndex() method from TabixReader is made private and it  is being used in the below location.

https://bitbucket.org/lorainelab/integrated-genome-browser/raw/42bca5fa9467f52a2b5c50baca74cf73889a9ff4/core/genometry/src/main/java/com/affymetrix/genometry/symloader/SymLoaderTabix.java
What would you suggest me on this?

Also if it's not too much to ask can you please review my changes relevant to upgrading to htsjdk in the  branch https://bitbucket.org/kkorey/kkorey-igb/branch/IGBF-1098-sam-so
It would really be of great help.

**Comment by koreykiran** [comment]
@lbergelson, I have managed successfully upgrade to the latest htsjdk version.

Since our project is an OSGI project, we are using a symbolic name attribute for one of the operations for normal maven projects we use project artifact id as a symbolic name.
So can we go ahead and submit a pull request which adds the attribute to the build.gradle while creating the jar?

Thanks in advance.

**Comment by lbergelson** [comment]
@koreykiran Sorry for the long absence, I got distracted and then was away for a while.  I'm glad you managed to upgrade without my help, sorry to disappear on you.   

I think it would be fine to add OSGI bundle information to manifest if that's helpful for OSGI projects.  I know nothing about it though, so I'm might not be seeing some downside.

**Comment by koreykiran** [comment]
@lbergelson Thanks for the help.
We also managed to add the library without the OSGi bundle information.
So I'm closing the issue.
