### ISSUE TITLE
Question using BlockCompressedInputStream + random access bam

### ISSUE THREAD

**Issue by lindenb** [samtools/htsjdk#1445]
Not an issue, but a request for an advice :-)

I'm trying to extract the reads for a given gene for all BAMs in Encode.

The problem is that the BAMs are not indexed  (eg   'https://www.encodeproject.org/files/ENCFF741DEO/@@download/ENCFF741DEO.bam'  ). Downloading the wole bam + streaming takes to much time.

```

$ wget -O -  'https://www.encodeproject.org/files/ENCFF741DEO/@@download/ENCFF741DEO.bam.bai' > /dev/null 
(...)
2019-12-13 20:46:26 ERROR 404: Not Found.

$  wget -O -  'https://www.encodeproject.org/files/ENCFF741DEO/@@download/ENCFF741DEO.bai' > /dev/null 
(...)
2019-12-13 20:46:32 ERROR 404: Not Found.


$ wget -O -  'https://www.encodeproject.org/files/ENCFF741DEO/@@download/ENCFF741DEO.bam' | file -
(...)
/dev/stdin: gzip compressed data, extra field
``` 

I sent a mail to Encode , asking theù to upload the bai files.

For now, my **crappy-friday-idea** is to read the file at random offsets and try to  uncompress + reading the reads. Run a **binary-search** until my region of interest is found.

So far, I implemented my idea here:  https://github.com/lindenb/jvarkit/blob/dc04882543448d91dfbc7e9bc6902bea8dbb6829/src/main/java/com/github/lindenb/jvarkit/tools/nobai/BamWithoutBai.java#L315

I read a large chunk of bytes, scan this array to find BlockCompressedStreamConstants.GZIP_ID1 and BlockCompressedStreamConstants.GZIP_ID2 (thank you John Marshall https://twitter.com/jomarnz/status/1205536219561648133 ) , and create a new BlockCompressedInputStream at this point.

I'm not sure if i should expect a very new SAM record as the first data in this BGZF block ? could it be broken ?

Can I use BlockCompressedInputStream to start reading a BGZF block at any point or does it expect to read  some kind of BGZF file header ?

Thank you for your answers + suggestion !

P.

**Comment by lbergelson** [comment]
I'm assuming the bams are sorted?  If not you're obviously out of luck.  What you're trying to do isn't as easy as you're hoping I think.  

You're making 2 key assumptions which are not safe: 
  1 That if you find a BGZF block start then you can safely assume that that is a block start.  
       Bam files are large enough that you are likely to run into what looks like block starts just by random chance.
  2. That a block always starts with a new SamRecord.   
     SamRecords can span multiple blocks.

However, you are in luck... because someone already implemented a robust way of doing this!

The [disq](https://github.com/disq-bio/disq) project includes code to do exactly what you want.  Jump to an approximate position in a bam file and search for SamRecord start sights.  It's been run against a very large cohort of bams to show that it doesn't have any known false positive start sites and very few false negative start sites (maybe 0... I can't remember).  

Look at the `BgzfBlockGuesser` and `BamRecordGuesser`. They're designed to be used with spark, but you should be able to either use directly or with slight modification.

**Comment by lindenb** [comment]
> The disq project includes code to do exactly what you want

@lbergelson  great !!!! thank you so much :-)

**Comment by lindenb** [comment]
@lbergelson FYI , I wrote the tool http://lindenb.github.io/jvarkit/BamWithoutBai.html . If i'm not lazy again, may be I'll wrote a BioRxiv paper and include you as an author.

 Thanks again.

**Comment by lbergelson** [comment]
@lindenb Neat!  I hope that the disq code was useful.  @tomwhite is really the author of disq, so any credit should go to him.  It's cool to see someone using it for something we hadn't thought of.

**Comment by lindenb** [comment]
@tomwhite @lbergelson FYI the origin of the BgzfBlockGuesser.java is cited in my code + readme. I'll try to write something in the next weeks..

**Comment by tomwhite** [comment]
@lindenb @lbergelson Glad to hear it's useful! BTW the guessing code is originally from the Hadoop-BAM project, so please cite that project too if you write something up.
