### ISSUE TITLE
Support IGV "browse mode" CRAM decoding

### ISSUE THREAD

**Issue by cmnbroad** [samtools/htsjdk#1597]
From the IGV request: Currently to decode a cram, you need to load an entire reference sequence (chromosome) for the region of interest.   This is a big performance hit when loading the fasta by URL, which most IGV users are doing.   This is not the case with cram.js,  it just loads a slice of the sequence for the MD5 check.

**Comment by cmnbroad** [comment]
To implement this we mainly need two things:

- full support for refget, so we can retrieve reference fragments (I believe htsjdk's reference retrieval code uses an older protocol that predates (is a precursor to ?) refget, and assumes retrieval of whole contigs.
- make internal changes to the reference contig offset calculations to support partial reference contig fragments

Unclear whether we also need to add a way for the caller (i.e., IGV) to engage this mode. We may want to just automatically use it when handed a URL source, although it's unclear how that might affect performance in the case where you're decoding a full CRAM. We also need to think about any ramifications for multi-reference slices.

**Comment by jrobinso** [comment]
@cmnbroad For IGV's purposes I do not think you do not need "refget",  IGV supplies the reference sequence when decoding CRAMs from IGV through an interface, it can easily be changed to supply reference fragments.    See https://github.com/igvteam/igv/blob/master/src/main/java/org/broad/igv/sam/cram/IGVReferenceSource.java.     

This interface (htsjdk.samtools.cram.ref.CRAMReferenceSource) was implemented to allow IGV (or other clients) to supply the sequence, since IGV must load sequence for the region in view for its own sequence track.
