### ISSUE TITLE
Iterator not working on vcffileReader

### ISSUE THREAD

**Issue by AlessandroBalestrucci** [samtools/htsjdk#1701]
### Description of the issue:
Not possible to invoke the iterator() method on object VCFFileReader

### Your environment:
version of htsjdk: 4.1.0
version of java: 17

### Steps to reproduce
 VCFFileReader vcfReader = new VCFFileReader(new File(vcf), false);
for (VariantContext variant: vcfReader.iterator()) {
	//some code here
			}

### Expected behaviour
It should complie

### Actual behaviour
Compile error: "Can only iterate over an array or an instance of java.lang.Iterable"

**Comment by cmnbroad** [comment]
@AlessandroBalestrucci It is a bit confusing, but you can't use for each on an `iterator`; only an `Iterable.` The correct syntax to use is:

`for (VariantContext variant: vcfReader)`

It should work fine if you do it that way.

**Comment by yfarjoun** [comment]
You can take a look at a project that uses htsjdk, for example Picard.

https://github.com/broadinstitute/picard/blob/master/src/main/java/picard/vcf/LiftoverVcf.java
has this use-case (one of many).

you should remove the `.iterator()` from you code, since the reader is
iterable, but the iterator is not...

Cheers,

Y.

**Comment by AlessandroBalestrucci** [comment]
Thanks everyone for your helps
