### ISSUE TITLE
What's with switching to "contig" everywhere?  It's not even correct/accurate?

### ISSUE THREAD

**Issue by tfenne** [samtools/htsjdk#197]
I just noticed that there are changes to many core classes (SAMRecord, VariantContext, Interval) to implement a new Locatable interface.  The main result seems to be deprecation of getChr(), getChrom() getChromosome(), getReference() etc. methods in preference to a new getContig().

I get the desire to standardize, but it's confusing to long time users of the library to suddenly change and deprecate all the existing method names.  But more to the point "contig" is not really even an accurate term for most uses.  For human, and most larger references genomes, the chromosomes are scaffolds of multiple contigs (contiguous sequences) assembled with Ns in the middle.  How about using something more generic like getReferenceSequence()?

**Comment by nh13** [comment]
@droazen @lbergelson @mattsooknah

**Comment by lbergelson** [comment]
We picked getContig() because it seemed like the most accurate name under a
dozen characters.  getReferenceSequence() seems confusing to me because I
would expect it to return the matched sequence at that point, i.e. the
actual bases.  getReferenceSequenceName() would be less confusing, but is
incredibly verbose.  getReference() is less confusing to me than
getReferenceSequence(), and is fairly compact.  It has the benefit of
aligning with GA4GH nomenclature, in which a reference is a
chromosome/contig identifier, and those are grouped into ReferenceSets.

**Comment by geoffjentry** [comment]
@lbergelson Where did the 12 character limitation come from? IDE auto-complete exists for a reason :)

**Comment by lbergelson** [comment]
12 characters is a random number I just chose, but for common functions that are called often, I would definitely prefer shorter names over marginally more clear long one. 

We will have lots of code that looks like 
```
new Something(x.getContig(), x.getStart(), x.getEnd())
```
which I think is worth preferring over the more explicit
```
new Something(x.getReferenceSequence, x.getStartPositionOnReference, x.getEndPositionOnReference)

**Comment by nh13** [comment]
@lbergelson but does this conform with the rest of this jdk?

**Comment by lbergelson** [comment]
`getChr()`, `getChrom()`,  `getChromosome()`, and `getSequence()` are all relatively short and equally ambiguous.  If people think that `getReference()` is clearer than `getContig()` we should change to that. None of these methods were long precise names.  

The fact that we have many classes implementing the same function with different names seems to point to the idea that no one of these names is strongly preferred to another, but that everyone prefers it to be relatively short.

**Comment by droazen** [comment]
@nh13 The rest of htsjdk is not self-consistent on this issue. What we have is a zoo of `getChr()`, `getChrom()` `getChromosome()`, `getReference()`, etc., across `htsjdk.samtools` / `htsjdk.tribble` / `htsjdk.variant`. When these three codebases were brought together, no effort was made to reconcile their various interfaces, which is why we have so many different names for the same operations and so many different implementations of things like intervals.

I'm fine with whatever name has majority support, as long as we agree to pick one and deprecate the others! :)

**Comment by vdauwera** [comment]
Might help to have a short manifesto that defines key terms and clarifies their scope, to avoid future multiplication of alternatives. 

Personally I don't think it matters if the term that ends up being chosen is not the most technically accurate, as long as it is defined explicitly and used consistently.

**Comment by lbergelson** [comment]
@vdauwera That's a good idea.

**Comment by tfenne** [comment]
@lbergelson makes the good point that GA4GH nomenclature for this is just "reference", and since that is both short and technically right (the best kind of right), perhaps that makes sense?

@vdauwera I definitely agree that having a glossary and clearly defined preferred terms for things would help going forward.

**Comment by vdauwera** [comment]
Can we consider this answered and close it, possibly with the condition to open a doc ticket to document the scope/definitions of key terms?
