### ISSUE TITLE
makeReadUnmapped in SamUtils creates possibly out-of-spec Sam files.

### ISSUE THREAD

**Issue by yfarjoun** [samtools/htsjdk#346]
SamUtil.makeReadUnmapped() unsets the setNotPrimaryAlignmentFlag thereby possibly creating two records that are both primary, have the same query name and are "first in pair". 

This seems to be out of spec with regards to section "1.2 Multiple mapping" in the sam-spec.

I would like to remove the line that unsets the "NotPrimaryAlignment" flag. 

Any comments?

@lh3 ?

**Comment by tfenne** [comment]
I think not having the method clear the "Not Primary Alignment" flag would also be weird though.  Because it makes no sense to have an unmapped read marked as not primary alignment.  I would suggest either:
a) It's the caller's responsibility to ensure that, when using this method, multiple reads with the same name and pair flags don't end up getting written to the same file, or
b) Add a check in this method to deny it being run on reads it should not be run on.

Regarding a) vs b) I could conceive of situations where I might want to iterate through a BAM file and pull out *only* secondary alignments, and revert/unmap them ready for some further analysis, so I'd be loathe to forbid passing secondary alignments to this method.

Also, it looks like this method never got updated to handle the `supplemental` flag, so it's currently split on handling of secondaries and supplementals.

**Comment by mattsooknah** [comment]
Also, currently ```SAMRecord.isValid()``` will throw a validation error if it finds unmapped reads with the secondary or supplementary flags set:
https://github.com/samtools/htsjdk/blob/b1a05dbaa32006f492ef52922c8e8dfeac5056da/src/java/htsjdk/samtools/SAMRecord.java#L1627

It's not clear if this is the correct behavior, since the SAM spec indicates that "If 0x4 is set, no assumptions can be made about RNAME, POS, CIGAR, MAPQ, and bits 0x2, 0x100, and 0x800."

So if we change ```SAMUtils.makeReadUnmapped()```, then we should also change ```SAMRecord.isValid()``` to be consistent. And in any case I agree with @tfenne that the secondary / supplementary behavior  should be consistent.

**Comment by tfenne** [comment]
@mattsooknah regarding `SAMRecord.isValid()` we made the decision long ago to "validate" more rigorously than the spec suggests, as it is often very helpful in finding bugs and problems.  The goal (not always correctly hit) is that validating at ValidationStringency.Strict should check for spec violations and additional problems/errors, and that Lenient should check only what's in the spec.

**Comment by mattsooknah** [comment]
In that case, I'd prefer clearing the secondary and supplementary flags, so that  ```makeReadUnmapped``` is compliant with ```ValidationStringency.Strict```. And make it the caller's responsibility to deal with any duplication issues that arise as a result.

**Comment by yfarjoun** [comment]
thanks!

**Comment by yfarjoun** [comment]
thanks for the discussion. will not change behaviour and will fix the split with supplemental (that is what instigated this issue, behind the scenes...)
