### ISSUE TITLE
Histogram caches computed mean, but does not recompute after all changes

### ISSUE THREAD

**Issue by tfenne** [samtools/htsjdk#347]
`Histogram`'s `getMean()` method caches the result in an instance variable.  An attempt is made to nullify the cached value when the histogram is mutated, but the attempt is not completely successful.  Since `Histogram` extends `TreeMap`, one can call methods like `remove()`, `clear()` etc. and after these calls the result of calling `getMean()` is incorrect.  It looks like even the `trimBy..()` methods use `remove()` but don't reset the value of `mean`.

I'm not sure why the mean is singled out for caching, whereas other values like the median are not.  My preference would be to just remove the caching of the mean value altogether.  If others agree, I'll submit a PR.

**Comment by tfenne** [comment]
@nh13 @yfarjoun What do you think?

**Comment by nh13** [comment]
I am trying to figure out why its even there.  Like you said, other values are not cached.  I thought for second that perhaps because there is a copy constructor, but that isn't used anywhere in Picard for example.  On the other hand, ```getStandardDeviation``` needs to use ```getMean``` so we would be computing the mean twice (see ```insertSizeMetricsCollector```).  Seems like a pre-mature optimization, since we don't cache the median and we do have a method ```getMedianAbsoluteDeviation``` that uses the ```getMedian```.  Since it is not clear that caching is needed, I err on the side of having correctness, so I would argue for removing the caching.

**Comment by yfarjoun** [comment]
I looked in our usages of Histogram.mean() and I only see places where the
current implementation may cause problems if someone add a call to mean
earlier in the code. I do not see anywhere that it would actually improve
runtime.

I agree that this should either be done right (by reimplementing all the
TreeMap functions to invalidate the cache, and also all the other member
functions that change the mean value) or as you suggest, remove the
optimization.

Given that I see no need for the optimization, I suppose removing the cache.

Yossi.

**Comment by davidbenjamin** [comment]
Closed by #348.
