### ISSUE TITLE
SAMWriterFactory.makeSAMOrBAMWriter creates BAM files with a ".cram" extension

### ISSUE THREAD

**Issue by cmnbroad** [samtools/htsjdk#366]
If you pass in a filename with a .cram extension, makeSAMOrBAMWriter will create a BAM file with a .cram extension and return a BAMFileWriter, which is probably not what was intended. This was causing many Hellbender tools to create BAM files with the .cram extension. Using makeWriter instead will remedy this (as it will create a real .cram file) but makeSAMOrBAMWriter should check the extension and either redirect to makeCRAMWriter or reject the request.

**Comment by cmnbroad** [comment]
This should probably throw if its handed a .cram extension since it doesn't accept a reference, so in the CRAM case it would only be useful with the download service or an embedded reference.

**Comment by tfenne** [comment]
I admit I haven't followed this all too closely, but I thought the reason for the entry in Defaults for `reference_fasta` was so that there was a way to specify a default reference fasta for CRAM so as not to need to update every single API?  I.e. could one call this to make a CRAM file in a JVM that was started with -Dsamjdk.reference_fasta=my.fasta?

**Comment by cmnbroad** [comment]
Yes, we could fix this so that if you had the environment variable set (or
the download service enabled) it could pick those up. We'd still need to
make the change to go down the CRAM path though. However, in the (common ?)
case where neither of those is true, the downstream failures may not be
obvious. So maybe we should have this check for a .cram extension, and
throw only if neither of default reference or download are set.
