### ISSUE TITLE
function for retrieveing secondary alignment misnamed

### ISSUE THREAD

**Issue by yfarjoun** [samtools/htsjdk#374]
The sam-spec calls the 0x100 flag "secondary alignment", but the htsjdk code it's accessed using getNotPrimaryAlignmentFlag(). This is probably a throwback to a time when there was no supplemental alignments, but now we have them....perhaps it's time to deprecate getNotPrimaryAlignmentFlag  and use instead a function named 
getSecondaryAlignmentFlag() ?

opinions?

**Comment by tfenne** [comment]
:+1:  I think the `notPrimaryAlignment` is still technically correct because I would argue that if the best alignment for a read is broken into multi segments that are not co-linear with the reference then the "primary alignment" is the set of records with the same name, pair flags and the `notPrimaryAlignment` bit not set.  So maybe I am in the mood for a semantic argument today after all :wink: 

That said, I'd be totally on board with deprecating the current name in favor of a clearer, shorter, more obviously correct method like `isSecondaryAlignment()`.

**Comment by magicDGS** [comment]
This can be closed by https://github.com/samtools/htsjdk/pull/977, no?
