### ISSUE TITLE
Order of attributes in SAM header and record

### ISSUE THREAD

**Issue by yfarjoun** [samtools/htsjdk#396]
The arrival of Java 8 to HTS-JDK also brought with it a change in the order of unordered collections like hash-maps and sets. This, in particular has changed the order of attributes in the header lines and possibly in the optional tags in a SAM record, causing tests that compare files rather than SAM headers and records to fail.

There are several solutions to this (that I see):

(From easiest and fastest to hardest and most involved)
1. Go over all the test files and change them for java 8, but leave the non-deterministic behavior to annoy in the next version of java. 
2. fix the tests so that they no longer compare files but instead compare objects, leaving the spec the same.
3. fix SAM spec and htsjdk code to have a particular order in the attributes (say, sorted by attribute tag). Then, go over all the test files and change them for java 8 and the new deterministic order. 

Any opinions? Any other ideas?

**Comment by akiezun** [comment]
i vote for 2. That's what we do in gatk4

**Comment by tfenne** [comment]
I would say that #2 would be best, but it is reasonable to do that quickly so that the Picard build can be fixed?

**Comment by tfenne** [comment]
@yfarjoun I don't think the problem is in HTSJDK.  I did some poking around and it appears that a few months ago someone (trigg?) modified `AbstractSAMHeaderRecord` to use a `LinkedHashMap` for attributes so that it would maintain insertion order.  The problem is that `IlluminaBasecallsToSam`'s insertion order was changing based on `HashMap` ordering.
