### ISSUE TITLE
opinions wanted: how to specify lossy parameters for CRAM?

### ISSUE THREAD

**Issue by vadimzalunin** [samtools/htsjdk#422]
CRAM lossy parameters are: 
- lossy read names (boolean)
- tags (list of tags to drop or to keep)
- quality score: drop, bin, preserve (more weird ones are omitted for now)

This could become a general filter/transform API but I'm also happy to keep it CRAM-specific, just need a way to pass this from a user to the code (CRAMFileWriter).

**Comment by cmnbroad** [comment]
Do you expect the number of these to evolve/vary with the CRAM version (as the spec evolves) ? Since it seems like there are already quite a few, it might make sense to replace the individual setters and getters on we have now on CRAMFileWriter with a separate CRAMOptions object that you can get/set, with a set of pre-populated defaults. 

We should also think about whether other parameters that are not necessarily preservation-related (such as default container/slice sizes, etc.) should be part of this as well. I know we have some support for setting those now but it might make sense to unify them.

**Comment by vadimzalunin** [comment]
@cmnbroad 
CRAMOptions is a good idea. Something like this? 
`SAMFileWriterFactory.makeCRAMWriter(..., CRAMOptions options)`

**Comment by cmnbroad** [comment]
@vadimzalunin - @droazen and I were talking yesterday about whether we might want to extend the existing SAMFileWriterFactory options pattern and add a "setOptions" or "setCompressionOptions" method on the factory. But it looks like the existing options that use this pattern are more generic; the one existing case where there is a compression parameter is the BAM compression level, which is passed as an argument to makeBAMWriter (though it can be set via system property). So I'd be inclined to just make this a (possibly versioned) CRAMOptions parameter to makeCRAMWriter. We'd probably want to have a getter, poplulated with default values in the case where the writer was created using one of the existing makeCRAMWriter apis.

**Comment by cmnbroad** [comment]
The CRAMEncodingStrategy class is threaded through all of the code and can be used for this since #1440.
