### ISSUE TITLE
SAMSequenceDictionaryExtractor doesn't handle CRAMs

### ISSUE THREAD

**Issue by cmnbroad** [samtools/htsjdk#731]
Just adding the cram extension to the list of extensions used by the SAM handler won't work unless a method overload is added that accepts a reference. Alternative it would be possible to have a custom handler that bypasses the SAMReader and just retrieves the header directly, since the reference isn't needed to just do that.

**Comment by yfarjoun** [comment]
I have an implementation of a solution that involves the following:

- an "empty" implementation of ReferenceSource (that does nothing and will throw an exception if you ask for the referenceBases)
- changing the default for MakeDefault of SamReaderFactory so that it will use that referenceSource by default (which will get overridden by any subsequent setReferenceSource, or setReferenceFile call)

Does that sounds like a reasonable solution?

**Comment by yfarjoun** [comment]
the implementation can be viewed here: #732

**Comment by cmnbroad** [comment]
One other option - it might be less intrusive to just crack the file open. Given a stream on the file, I think its a one-liner to get the header without the reference, i.e.:

CramIO.readCramHeader(inputStream).getSamFileHeader()

**Comment by cmnbroad** [comment]
This was fixed in #1308.
