### ISSUE TITLE
Question: something like `Pair<Iterator> = equal_range` for TabixReader  ?

### ISSUE THREAD

**Issue by lindenb** [samtools/htsjdk#931]
Not a bug but a question:

I'm currently annotating a large VCF with the **gnomad** dataset. It takes some hours because a TabixReader.query (= random access on disk isn't it ? ) is invoked for each variant in my file. (or is there a better strategy ?)

As my VCF file is sorted and is using the same dictionary than gnomad, is there a mechanism in htsjdk to 
speed up things by keeping tracks of the position that have already been seen in tabix (I'm thinking of something similar to `C++ map.equal_range` which is more faster that `map.find` )

If not, is it feasible ? Do you have any suggestion for a strategy ?

**Comment by yfarjoun** [comment]
the GATK frame engine has a way to iterate over multiple "ROD"s (Reference Ordered Data) in parellel. Have you looked into using that? 

otherwise, you could manually iterate over both vcfs (using iterator, not query) and deal with inconsistencies as they arise (if they are not at the same position, advancing the later one, and if they are in the same position, advancing them both.)...

I'm not sure that this answers your question though....

**Comment by lindenb** [comment]
@yfarjoun  thanks, that was useful

**Comment by tfenne** [comment]
@lindenb I don't think we have anything like this in HTSJDK, but this is only a few lines of scala and does more or less what you're asking for I think:

https://github.com/fulcrumgenomics/fgbio/blob/4c4a68181bd38dc9b23270ff13bfc97a23bad951/src/main/scala/com/fulcrumgenomics/vcf/JointVariantContextIterator.scala

Takes two or more variant context iterators and produces an Iterator of Seq (ordered collection) of `Option[VariantContext]`, over the union of sites across all the iterators.  It's not smart about the fact that the same variant can be detected at different positions if the set of indel alleles varies, but otherwise does a fine job.

**Comment by lindenb** [comment]
@yfarjoun yes, I've already got something like this: 

https://github.com/lindenb/jvarkit/blob/master/src/main/java/com/github/lindenb/jvarkit/tools/vcfcmp/EqualRangeVcfIterator.java#L58

(it returns an Array of VariantContext in the database.vcf that are 'equals()' to the current user's variant)

My problem is I would like something between a 'read-all' and a bunch of random-access jumps. e.g: annotating a very large number of variants with gnomad that are on the 3' end of chr1 == I'd like to avoid to scan all the useless 5' part of the gnomad-chr1 :-) I'm still exploring the subject ....
