### ISSUE TITLE
Performance issues with VCF header parsing

### ISSUE THREAD

**Issue by SquidDev** [samtools/htsjdk#934]
When parsing VCF files with a large number of `##contig` headers (32k in this case), a significant amount of time is spent processing them (about 60 seconds on my machine).

I've done a small amount of profiling with VisualVM, with the result ending up looking something like this:
![image](https://user-images.githubusercontent.com/4346137/28231798-45d3d46c-68e5-11e7-9ef8-1d43f8e806f8.png)

Running `PrintVariantsExample` on a such a file results in [this log](https://gist.githubusercontent.com/SquidDev/c1a17641322a97b11a1fd82a97aed633/raw/5001506f1f20579862d625bb691b0549a1cedc79/htsjdk.variant.example.PrintVariantsExample.log).

### Your environment
* version of htsjdk: 2.10.1
* version of java: Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
* which OS: Windows 10

### Steps to reproduce
This can be tested by running `htsjdk.variant.example.PrintVariantsExample` with [this](https://gist.githubusercontent.com/SquidDev/74521af2a5e32f3b48d00cf75c22b1a1/raw/8862e99d8da90196dd89bc0f7f0ea058e78ea1dc/Sample01.vcf) VCF file.

**Comment by cmnbroad** [comment]
This issue will be fixed by https://github.com/samtools/htsjdk/pull/835. The current VCFHeader implementation checks for duplicates every time a new contig line is encountered by doing a string compare with every existing contig line, which scales quadratically. The new implementation replaces this with a hash probe. On my machine, running PrintVariantsExample on the attached .vcf with 32k header lines takes around 30 seconds; on the branch it takes .6 seconds.

**Comment by cmnbroad** [comment]
Fixed via https://github.com/samtools/htsjdk/pull/968.
