### ISSUE TITLE
variantcontext uniqueness 

### ISSUE THREAD

**Issue by mcgml** [samtools/htsjdk#935]
I'd like to create a unique set of variantcontexts but hashcode and equals are inherited from Object. Could these be overridden? Or is there are another way to do this?

**Comment by magicDGS** [comment]
Without modifying the underlying code in htsjdk, you have two options:

* Implement your own wrapper around `VariantContext`overriding equals and hashCode to include the information that you need for uniqueness.
* Use a `TreeSet` with your own comparator, and implement there the logic to consder equals two `VariantContext`.

I think that one of the major issues of implementing equals/hashCode in `VariantContext` is to decide which information should be included: FORMAT annotations? genotypes with/without annotations? There are too many variables to compare the variants and genotypes, so I think that it is better to use your own logic here instead of relying on default behavior implemented in HTSJDK...

**Comment by mcgml** [comment]
Thanks @magicDGS I went with option one: extending the variant context class and overriding hashcode & equals as suggested, I now see why this is not default!
